- plugin.xml
Error: Unable to instantiate receiver
com.instabug.library.network.InstabugNetworkReceiver
> fix Error: Unable to instantiate receiver

- src/android/IBGPlugin.java
- www/instabug.js
@DevHossamHassan @Figo0o Can someone please review this PR?
> :bug: Fix a bug where invocation for iOS was not working properly

- CHANGELOG.md
- README.md
- package.json
- plugin.xml
- scripts/android/link_gradle.js
- scripts/android/unlink_gradle.js
- src/android/IBGPlugin.java
- src/android/IBGPluginActivity.java
* Fixes missing imports in android.
* Fixes floatingButtonEdge & floatingButtonOffset on android.
* Adds script to automatically add our maven repo to the project level `build.gradle`
> Hotfixes 8.6.4

- .circleci/config.yml
- sampleApp/platforms/android/app/build.gradle
- sampleApp/platforms/android/app/src/androidTest/java/com/instabug/cordova/plugin/InvokeInstabugUITest.java
- sampleApp/platforms/android/app/src/test/java/com/instabug/cordova/plugin/IBGPluginTests.java
- sampleApp/www/js/index.js
- src/android/IBGPlugin.java
* Refactor IBGPlugin
* Adds first android unit test for IBGPlugin
> Refactor IBGPlugin Execute and adds unit tests

- plugin.xml
* Bump version in plugin.xml to match package.json
> Bump plugin version to 9.1.0

- www/bugReporting.js
Incompatible es2015 `let` keyword is causing an issue for a user.
> Replace let with var

- sampleApp/platforms/ios/CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewNavigationDelegate.m
Fixes https://github.com/Instabug/instabug-cordova/issues/90
> Invoke UIApplication method on the UI thread

- src/android/IBGPlugin.java
> Fix locale on Android

- sampleApp/platforms/android/app/src/test/java/com/instabug/cordova/plugin/IBGPluginTests.java
- sampleApp/platforms/android/platform_www/plugins/instabug-cordova/www/instabug.js
- src/android/IBGPlugin.java
- src/ios/IBGPlugin.m
```
cordova.plugins.instabug.setColorTheme("light");
cordova.plugins.instabug.setColorTheme("dark");
```
> [IBGBUGCHAT-10513] Map API: setColorTheme

- .github/pull_request_template.md
Updated the default PR template to enforce our checklist.
N/A
> Added default PR template

- src/ios/IBGPlugin.h
- src/ios/IBGPlugin.m
- Add iOS API setUserAttribute
> [MOB-4687] Add iOS API setUserAttribute

- src/ios/IBGPlugin.h
- src/ios/IBGPlugin.m
Added iOS APIs:
- `setUserAttribute`
- `removeUserAttribute`
- `getUserAttribute`
- `getAllUserAttributes`
> [MOB-4694] Feature/User Attrs iOS APIs

- README.md
- Revisit README format.
- Document the unsupported features.
- Remove irrelevant info from the integration steps.
- Add the compileSdkVersion requirement.
> [MOB-4565] Update README.md

- .circleci/config.yml
- Update brew commands to fix failing CI on master.
> [MOB-5609] Update brew commands

- CHANGELOG.md
- plugin.xml
> Remove Multidex dependency

- src/android/IBGPlugin.java
> Fix APIs Callback on Android

- src/android/IBGPlugin.java
- src/android/util/ArgsRegistry.java
- src/ios/IBGPlugin.m
- src/ios/util/ArgsRegistry.h
- src/ios/util/ArgsRegistry.m
- www/ArgsRegistry.js
- www/BugReporting.js
- www/Instabug.js
> Move `setVideoRecordingFloatingButtonPosition` to `BugReporting`

- package.json
- www/index.js
Improve Ionic import syntex:
```js
import {
Instabug,
BugReporting,
FeatureRequests,
Surveys,
Replies,
} from "instabug-cordova";
```
> Add Entry File for Ionic

- CHANGELOG.md
> Release CHANGELOG

- .circleci/config.yml
- Fixes CI Publish Job format.
> [MOB-9116] Fix CI Publish Job

- CHANGELOG.md
- example/tests/src/android/androidTest/InvokeInstabugUITest.java
- plugin.xml
> [MOB-10051] Bump Android SDK to v11.4.1

- CHANGELOG.md
- plugin.xml
> [MOB-10052] Bump iOS SDK to v11.2.0

- CHANGELOG.md
- example/package-lock.json
- package.json
- plugin.xml
> [MOB-10053] Bump Version to 11.2.0

- .circleci/config.yml
> [MOB-10068] Install Dependencies in Publish Job

- CHANGELOG.md
- example/package-lock.json
- package.json
- plugin.xml
> [MOB-10382] Release `v11.3.0`

- CHANGELOG.md
> [MOB-11724] Format Changelog
